Functionality to capture user activities
DostEducation/whatsapp-webhook-analytics pull request #23
Opened 2024-05-02 03:44 UTC by Sachinbisht27

#17 

### Please complete the following steps and check these boxes before filing your PR:

### Types of changes

- [ ] Bug fix (a change which fixes an issue)
- [ ] New feature (a change which adds functionality)

### Short description of what this resolves:

### Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] The code follows the style guidelines of this project.
- [ ] The code changes are passing the CI checks
- [ ] I have documented my code wherever required.
- [ ] The changes requires a change to the documentation.
- [ ] I have updated the documentation based on the my changes.
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.\

2024-05-07 15:54 UTC, Satendra-SR requested changes
@Sachinbisht27 a few changes are required. Have a look

2024-05-07 15:54 UTC, Satendra-SR commented on api/models/user_activities.py
> +    def get_started_activity_for_user(self, user_id, user_phone):
shouldn't it be like this?
```suggestion
    def get_todays_started_activity_for_user(self, user_id, user_phone):
```

2024-05-07 15:54 UTC, Satendra-SR commented on api/models/user_activities.py
> +    def get_succeeded_activity_for_user(self, user_id, user_phone):
same here

2024-05-07 15:54 UTC, Satendra-SR commented on api/models/user_flows.py
> +    def get_latest_flow_log_today(self, flow_uuid, user_phone):
```suggestion
    def get_todays_latest_user_flow(self, flow_uuid, user_phone):
```

2024-05-07 15:54 UTC, Satendra-SR commented on api/services/flow_run_log_service.py
>                  user_flow_log = self.create_log(flow_uuid, flow_name, flow_type)
We should create a new log only if the start node is available - ie flow_status == "Started", thoughts?

2024-05-07 15:54 UTC, Satendra-SR commented on api/services/user_activities_service.py
> +    def handle_user_activities(self, json_data: Dict[str, Any]):
Can we make it consistent? `json_data: Dict[str, Any]`?

2024-05-07 15:54 UTC, Satendra-SR commented on api/services/user_activities_service.py
> +    def create_or_update_user_activity(
Let's divide this function into multiple sub-functions that will perform only "Single Responsibility"?

2024-05-07 16:34 UTC, Sachinbisht27 commented on api/services/flow_run_log_service.py
>                  user_flow_log = self.create_log(flow_uuid, flow_name, flow_type)
Yes, thanks for the suggestion. Let me update that.

2024-05-07 16:56 UTC, Sachinbisht27 commented on api/services/user_activities_service.py
> +    def create_or_update_user_activity(
Sure @Satendra-SR. Let me do this.

2024-05-07 17:00 UTC, Sachinbisht27 commented on api/services/user_activities_service.py
> +    def handle_user_activities(self, json_data: Dict[str, Any]):
Sure

2024-05-08 06:38 UTC, Sachinbisht27 commented on api/services/user_activities_service.py
> +    def handle_user_activities(self, json_data: Dict[str, Any]):
Sure we can do this. Thanks for sharing.

2024-05-08 08:17 UTC, Satendra-SR reviewed
@Sachinbisht27 a few comments before we merge the changes. Have a look

2024-05-08 08:17 UTC, Satendra-SR commented on .pre-commit-config.yaml
> +- repo: https://github.com/sondrelg/pep585-upgrade
Why do we need this? 
The GitHub repo is archived now, if this is helpful , we may need to find an alternative -  https://github.com/sondrelg/pep585-upgrade

2024-05-08 08:17 UTC, Satendra-SR commented on api/services/user_activities_service.py
> +    def create_started_activity(
create Start activity should be similar to create activity, no? Can we do it like this in that case?
```suggestion
    def create_activity(
```

2024-05-08 08:17 UTC, Satendra-SR commented on api/services/user_activities_service.py
> +            completed_on=None,
don't we have default column values as `None` for these columns? What if we don't add them from here?

2024-05-08 08:53 UTC, Sachinbisht27 commented on .pre-commit-config.yaml
> +- repo: https://github.com/sondrelg/pep585-upgrade
I was exploring some pre-commit hooks so, we can maintain the TypeHinting in the codebase. I found 2 hooks related to it so added them here. I can explore more if this one is archived now.

2024-05-08 08:54 UTC, Sachinbisht27 commented on api/services/user_activities_service.py
> +    def create_started_activity(
Yes, Sure.

2024-05-08 08:57 UTC, Sachinbisht27 commented on api/services/user_activities_service.py
> +            completed_on=None,
We can remove them from here as not needed while creating new activity. We want the default value as null only.

2024-05-08 09:10 UTC, Satendra-SR approved these changes

2024-05-08 09:11 UTC, merged