Scaffolding of a FastAPI app for WhatsApp analytics
DostEducation/whatsapp-webhook-analytics pull request #5
Opened 2024-04-13 11:54 UTC by Sachinbisht27

#3

### Please complete the following steps and check these boxes before filing your PR:

### Types of changes

- [ ] Bug fix (a change which fixes an issue)
- [x] New feature (a change which adds functionality)

### Short description of what this resolves:

### Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] The code follows the style guidelines of this project.
- [ ] The code changes are passing the CI checks
- [ ] I have documented my code wherever required.
- [ ] The changes requires a change to the documentation.
- [ ] I have updated the documentation based on the my changes.
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.\

2024-04-13 12:44 UTC, Satendra-SR commented on .pre-commit-config.yaml
> +    -   id: check-added-large-files
There are a few more hooks which can be helpful for our usecase
1. **flake8** - Purpose: Runs the Flake8 code linter to check for PEP 8 violations and other style issues.
2. **black** - Purpose: Applies the Black code formatter to format Python code according to PEP 8 standards.
3. **isort** - Purpose: Sorts import statements in Python files according to PEP 8 guidelines.
4. **mypy** - Purpose: Runs the MyPy static type checker to find type errors in Python code.
5. **docformatter** - Purpose: Formats docstrings in Python files to adhere to PEP 257 guidelines.

2024-04-15 10:33 UTC, Sachinbisht27 commented on .pre-commit-config.yaml
> +    -   id: check-added-large-files
Added a few more hooks in the `pre-commit config`.

2024-04-18 05:45 UTC, Satendra-SR approved these changes

2024-04-18 05:46 UTC, Satendra-SR requested changes
Added some changes in the last review, got approved mistakenly

2024-04-18 11:05 UTC, Sachinbisht27 commented on .github/workflows/pre-commit.yml
> +    branches: [main]
Updated

2024-04-18 11:08 UTC, Sachinbisht27 commented on README.md
> +    source ./venv/bin/activate
Added command for win-os

2024-04-18 11:08 UTC, Sachinbisht27 commented on README.md
> +    pip install -r requirements-dev.txt
Merged

2024-04-18 11:09 UTC, Sachinbisht27 commented on config.py
> +load_dotenv()
Sure, @Satendra-SR Moved the `load_dotenv()` to the environment condition.

2024-04-18 11:12 UTC, Sachinbisht27 commented on .pre-commit-config.yaml
> +    -   id: check-added-large-files
Yes, @Satendra-SR. For the code formatting and increasing readability of the code.

2024-04-18 11:30 UTC, Satendra-SR commented on migrations/env.py
> +target_metadata = models.Base.metadata
Can we try this?

target_metadata = db.metadata

2024-04-18 12:09 UTC, Satendra-SR approved these changes
A few questions, else looks good to go

2024-04-18 12:14 UTC, Sachinbisht27 commented on api/utils/loggingutils.py
> +logging.basicConfig(level=logging.DEBUG)
Sure, updating.

2024-04-18 12:14 UTC, Sachinbisht27 commented on config.py
> +    load_dotenv(path.join(basedir, ".env"))
Updated

2024-04-18 12:16 UTC, merged